language: rust
before_install:
  - sudo apt-get update
  - sudo apt-get install -y google-perftools  libgoogle-perftools-dev musl-tools
  - rustup target add x86_64-unknown-linux-musl

matrix:
  include:
    - os: linux 
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl

scipt: cargo test --target "$TARGET" --target-dir=/tmp/heca

before_deploy: cargo build --target "$TARGET" --release --target-dir=/tmp/heca

deploy:
  skip_cleanup: true
  file: "/tmp/heca/x86_64-unknown-linux-musl/release/heca"
  provider: releases
  edge: true
  draft: true
  on:
    tags: false
