[package]
name = "heca"
version = "0.0.4"
authors = ["picked name <ipickedaname@mail.com>"]
edition = '2018'
repository = "https://gitlab.com/heca/heca"
description = "Hebrew calendar utility"
keywords = ["calendar", "hebrew", "jewish"]
categories = ["command-line-utilities", "date-and-time"]
license = "MIT"

[dependencies]
lazy_static = "1.2.0"
chrono = "0.4"
time = "0.1.42"
enum_primitive = "0.1.1"
num = "0.2.0"
atoi = "0.3.1"
chrono-english="0.1.4"
clap = {version = "2.32.0", features = ["yaml"]}
heca-lib = {version="0.0.5", path="lib/heca-lib"}

[workspace]
members = ["lib/heca-lib"]
