[package]
name = "heca"
version = "0.0.3"
authors = ["picked name <ipickedaname@mail.com>"]
edition = '2018'
repository = "https://gitlab.com/heca/heca"
description = "Hebrew Calendar library."
keywords = ["library", "calendar", "hebrew", "jewish"]
categories = ["command-line-utilities", "date-and-time"]
license = "MIT"

[dependencies]
lazy_static = "1.2.0"
chrono = "0.4"
time = "0.1.42"
enum_primitive = "0.1.1"
num = "0.2.0"
atoi = "0.3.1"
chrono-english="0.1.4"
clap = {version = "2.32.0", features = ["yaml"]}
heca-convert-lib = {path="lib/heca-convert-lib"}
heca-yomtov-lib = {path="lib/heca-yomtov-lib"}

[workspace]
members = ["lib/heca-convert-lib", "lib/heca-yomtov-lib"]
