[package]
name = "heca"
version = "0.0.1"
authors = ["hebluach <hebluach@github.com>"]
edition = '2018'
repository = "https://github.com/hebluach/hc-rust"
description = "Hebrew Calendar library."
keywords = ["library", "calendar", "hebrew", "jewish"]
categories = ["command-line-utilities", "date-and-time"]
license = "MIT"

[dependencies]
lazy_static = "1.2.0"
chrono = "*"
time = "*"
enum_primitive = "*"
num = "*"
