[package]
name = "heca"
version = "1.0.0"
authors = ["picked name <ipickedaname@mail.com>"]
edition = '2018'
repository = "https://github.com/heca-project/heca"
description = "Hebrew calendar utility"
keywords = ["calendar", "hebrew", "jewish"]
categories = ["command-line-utilities", "date-and-time"]
license = "MIT"
readme = "README.md"
maintenance = { status = "actively-maintained" }

[dependencies]
lazy_static = "1.4"
chrono = {version = "0.4", features = ["serde"]}
time = "0.1"
enum_primitive = "0.1"
num = "0.2"
atoi = "0.3"
chrono-english="0.1"
clap = {version = "2.33", features = ["yaml"]}
heca-lib = "1.0"
either = {version = "1.5", features = ["serde"]}
itoa = "0.4"
rayon = "1.2"
xdg = "2.2"
serde = "1.0"
serde_json = "1.0"
smallvec = "1.0"
toml = "0.5"

[profile.release]
lto = true
debug = true
overflow-checks = true

[dev-dependencies]
assert_cmd = "0.11"
predicates = "1"
lazy_static = "1.3"


